id=hollowengine-video
name=HollowEngine Video
version=${version}
entry=ru.hollowhorizon.hollowengine.addons.video.HollowVideoAddon
environment=client
requiredClasses=org.bytedeco.ffmpeg.global.avformat,org.bytedeco.javacpp.Loader
