package ru.hollowhorizon.hollowengine.client.gui.scripting.panels

import de.fabmax.kool.modules.ui2.UiScope
import de.fabmax.kool.modules.ui2.docking.Dock
import ru.hollowhorizon.hollowengine.client.gui.docs.DocsNode
import ru.hollowhorizon.hollowengine.client.gui.scripting.FileNode
import ru.hollowhorizon.hollowengine.common.scripting.core.completion.ScriptColorizer
import ru.hollowhorizon.hollowengine.docs.pages.CreditsPage
import ru.hollowhorizon.hollowengine.docs.pages.ScriptingPage
import ru.hollowhorizon.hollowengine.docs.pages.WelcomePage
import ru.hollowhorizon.hollowengine.docs.pages.story.StoryEventsPage
import ru.hollowhorizon.hollowengine.docs.pages.story.npcs.CreationPage
import ru.hollowhorizon.hollowengine.docs.pages.story.npcs.NpcsPage

class DocsTreePanel(dock: Dock) : DockPanel("hollowengine.gui.ide.docs", dock) {
    override val icon = "hollowengine:textures/gui/icons/docs.png"

    override fun UiScope.compose() {
        docsTree()
    }

    val docsTree = DocsNode("HollowEngine", "").apply {
        initPages()

        isFolder = true
        children += DocsNode("welcome", WelcomePage)
        children += DocsNode("credits", CreditsPage)
        children += DocsNode("scripting", ScriptingPage).apply {
            isFolder = true
            children += DocsNode("scripting/story_events", StoryEventsPage).apply {
                isFolder = true
                children += DocsNode("scripting/story_events/npcs", NpcsPage).apply {
                    isFolder = true
                    children += DocsNode("scripting/story_events/npcs/creation", CreationPage)
                    children += DocsNode("scripting/story_events/npcs/options")
                    children += DocsNode("scripting/story_events/npcs/actions")
                    children += DocsNode("scripting/story_events/npcs/animations")
                    children += DocsNode("scripting/story_events/npcs/quests")
                    children += DocsNode("scripting/story_events/npcs/trading")
                }
                children += DocsNode("scripting/story_events/scene").apply {
                    isFolder = true
                    children += DocsNode("scripting/story_events/npcs/world")
                    children += DocsNode("scripting/story_events/scene/dialogues")
                    children += DocsNode("scripting/story_events/scene/camera")
                    children += DocsNode("scripting/story_events/scene/transitions")
                    children += DocsNode("scripting/story_events/scene/particles")
                    children += DocsNode("scripting/story_events/npcs/shaders")
                }
                children += DocsNode("scripting/story_events/players").apply {
                    isFolder = true
                }
                children += DocsNode("scripting/story_events/utils").apply {
                    isFolder = true
                }
            }
        }
    }.resize()

    fun initPages() {
        CreationPage.creationTemplate.apply {
            clear()
            addAll(
                ScriptColorizer.parse(
                    "create.story.kts", """
            // Declare the 'vitalik' variable
            val vitalik = npc(
                name = "Vitalik", // Character name that will be visible in chat and above head by default
                pos = pos(0, 0, 0), // Spawn coordinates
                world = "minecraft:overworld", // Dimension where the character will spawn
                model = "hollowengine:models/entity/player_model.gltf", // Path to character model
                rotation = rotation(180, 0), // Initial rotation (pitch and yaw axes)
                size = 1f to 1.2f, // Character hitbox size (Width and Height)
                attributes = mapOf( // Character attributes (health, speed, or mod-added properties)
                    "my_mod_id:my.best.attrubute_one" to 10f,
                    "my_mod_id:my.best.attribute_two" to 0.5f,
                ),
                textures = mapOf( // Texture replacements (original and replacement textures)
                    // Original texture is defined in model file or generated by engine. Use `/hollowengine model` command to find texture names
                    "model/texture_id_one" to "my_mod_id:path/to/my_best_texture.png",
                    "model/texture_id_two" to "my_mod_id:path/to/my_another_texture.png",
                ),
                animations = mapOf( // Replacing automatically detected animations with your own
                    AnimationType.IDLE to "bestIdleAnimation",
                    AnimationType.WALK to "walkAnimLoop",
                ),
                transform = Transform( // Adjust model position relative to entity center
                    tX = 1.1f, tY = 0.4f, tZ = 3f, // Model offset on X, Y and Z axes
                    rX = 90f, rY = 2.4f, rZ = 194f, // Model rotation around X, Y and Z axes
                    sX = 0.1f, sY = 1.001f, sZ = 9.2f // Model scale on X, Y and Z axes
                ),
                showName = false, // Show/Hide the name tag above character's head
                inverseHeadRotation = true, // Swap X and Y in head rotation (some models might have mixed axes)
            )
        """.trimIndent()
                )
            )
        }
    }

    private fun FileNode.resize(depth: Int = 0): FileNode {
        this.depth = depth
        children.forEach { it.resize(depth + 1) }
        return this
    }
}