org.gradle.jvmargs=-Xmx4096m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=true
kotlin.incremental=true

bookshelfVersion=16.3.20
stagesVersion=11.1.5
mcVersion=1.19.2
forgeVersion=43.4.2
modVersion=1.6.1
mappingsVersion=2022.11.27
hcVersion=1.6.3
kffVersion=3.12.0
ksffVersion=1.3