org.gradle.jvmargs=-Xmx6096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=false

hollowcore=2.2.6b
koolVersion=0.17.0-0mods-SNAPSHOT
compiler_plugin=1.5

modName=HollowEngine
modAuthor=HollowHorizon
modId=hollowengine
modVersion=2.0.0-Beta3
license=MIT

kotlinVersion=2.1.20-Beta2

publish.modrinth=XMd2cJSg
publish.curseforge=906892