org.gradle.jvmargs=-Xmx6096m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.daemon=false

compiler_plugin=1.4a

mod_name=HollowEngine
mod_author=HollowHorizon
mod_id=hollowengine
mod_version=2.0.0a
java_version=21
license=MIT

imguiVersion=1.87.3
kotlinVersion=2.1.0-Beta2

publish.modrinth=XMd2cJSg
publish.curseforge=906892