id=hollowengine-physics
name=HollowEngine Physics
version=${version}
entry=ru.hollowhorizon.hollowengine.addons.physics.HollowPhysicsAddon
environment=client
requiredClasses=com.github.stephengold.joltjni.Jolt
