package ru.hollowhorizon.hollowengine.client.ui.ide.timeline.ui

internal object CutsceneLang {
    private const val ROOT = "hollowengine.gui.ide.cutscene."

    const val PROPERTIES = ROOT + "properties"
    const val TRACKS = ROOT + "tracks"

    const val VIEW_DOPE_SHEET = ROOT + "view.dope_sheet"
    const val VIEW_CURVES = ROOT + "view.curves"
    const val FRAME_CURVES = ROOT + "view.frame_curves"

    const val CAPTURE_KEYFRAME = ROOT + "action.capture"
    const val ADD_KEYFRAME = ROOT + "action.add_keyframe"
    const val DELETE_SELECTED = ROOT + "action.delete_selected"
    const val SMOOTH_SELECTED = ROOT + "action.smooth_selected"
    const val CURVE_PRESET = ROOT + "action.curve_preset"
    const val COPY_SELECTED = ROOT + "action.copy_selected"
    const val CUT_SELECTED = ROOT + "action.cut_selected"
    const val PASTE = ROOT + "action.paste"
    const val CAMERA_PREVIEW_ON = ROOT + "action.camera_preview_on"
    const val CAMERA_PREVIEW_OFF = ROOT + "action.camera_preview_off"
    const val SAVE = ROOT + "action.save"
    const val LOAD = ROOT + "action.load"
    const val CANCEL = ROOT + "action.cancel"
    const val CLOSE = ROOT + "action.close"

    const val SAVE_TITLE = ROOT + "dialog.save_title"
    const val LOAD_TITLE = ROOT + "dialog.load_title"
    const val NAME = ROOT + "dialog.name"
    const val NO_CUTSCENES = ROOT + "dialog.no_cutscenes"

    const val PREVIEW = ROOT + "section.preview"
    const val ORIGIN = ROOT + "section.origin"
    const val KEYFRAME = ROOT + "section.keyframe"
    const val KEYFRAMES = ROOT + "section.keyframes"
    const val INTERPOLATION = ROOT + "section.interpolation"
    const val WORK_AREA = ROOT + "section.work_area"
    const val SELECTION = ROOT + "section.selection"

    const val CAMERA_ON = ROOT + "preview.camera_on"
    const val CAMERA_OFF = ROOT + "preview.camera_off"
    const val PLAYING = ROOT + "preview.playing"
    const val PAUSED = ROOT + "preview.paused"
    const val CURRENT_TIME = ROOT + "preview.current_time"
    const val DURATION = ROOT + "preview.duration"

    const val ORIGIN_X = ROOT + "origin.x"
    const val ORIGIN_Y = ROOT + "origin.y"
    const val ORIGIN_Z = ROOT + "origin.z"
    const val ORIGIN_YAW = ROOT + "origin.yaw"
    const val ORIGIN_MOVE_HERE = ROOT + "origin.move_here"
    const val ORIGIN_REBASE = ROOT + "origin.rebase"

    const val TIME = ROOT + "keyframe.time"
    const val VALUE = ROOT + "keyframe.value"
    const val CHANNEL = ROOT + "keyframe.channel"
    const val WORLD = ROOT + "keyframe.world"
    const val WORLD_ROTATION = ROOT + "keyframe.world_rotation"
    const val DELETE_KEY = ROOT + "keyframe.delete_key"
    const val DELETE_KEYS = ROOT + "keyframe.delete_keys"
    const val NO_SELECTION = ROOT + "keyframe.no_selection"
    const val END = ROOT + "keyframe.end"

    const val HANDLES = ROOT + "handles.title"
    const val HANDLES_AUTO = ROOT + "handles.auto"
    const val HANDLES_MIRRORED = ROOT + "handles.mirrored"
    const val HANDLES_ALIGNED = ROOT + "handles.aligned"
    const val HANDLES_FREE = ROOT + "handles.free"
    const val HANDLES_AUTO_HINT = ROOT + "handles.auto_hint"
    const val HANDLE_IN = ROOT + "handles.incoming"
    const val HANDLE_OUT = ROOT + "handles.outgoing"

    const val LAYER_SETTINGS = ROOT + "layer.settings"
    const val PROPERTY_SETTINGS = ROOT + "property.settings"
    const val LAYER_WEIGHT = ROOT + "layer.weight"
    const val LAYER_VISIBLE = ROOT + "layer.visible"
    const val LAYER_LOCKED = ROOT + "layer.locked"
    const val LAYER_DELETE = ROOT + "layer.delete"
    const val BLEND_MODE = ROOT + "layer.blend_mode"
    const val BLEND_OVERRIDE = ROOT + "blend.override"
    const val BLEND_ADD = ROOT + "blend.add"
    const val BLEND_SUBTRACT = ROOT + "blend.subtract"
    const val BLEND_MULTIPLY = ROOT + "blend.multiply"

    const val ROTATION_MODE = ROOT + "rotation.mode"
    const val ROTATION_EULER = ROOT + "rotation.euler"
    const val ROTATION_QUATERNION = ROOT + "rotation.quaternion"
    const val ROTATION_MODE_HINT = ROOT + "rotation.mode_hint"

    const val LIMITS = ROOT + "limits.title"
    const val LIMITS_HINT = ROOT + "limits.hint"
    }
