modLoader = "kotlinforforge"
loaderVersion = "[3,)"
license = "All Rights Reserved"
[[mods]]
modId = "hollowengine"
version = "${file.jarVersion}"
displayName = "HollowEngine Legacy" # Don't change it! This may break the game!
description = '''
'''

[[dependencies.hollowengine]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "hc"
mandatory = true
versionRange = "[1.19.2-1.6.3,1.19.2-1.7.0)"
ordering = "AFTER"
side = "BOTH"
[[dependencies.hollowengine]]
modId = "kotlinscript"
mandatory = true
versionRange = "[1.4,)"
ordering = "AFTER"
side = "BOTH"
