id=hollowengine-compiler
name=HollowEngine Kotlin Compiler
version=${version}
entry=ru.hollowhorizon.hollowengine.common.ScriptingEnvironmentInitializerImpl
environment=common
requiredClasses=org.jetbrains.kotlin.scripting.compiler.plugin.ScriptCompilerProxy
