id=hollowengine-acoustic
name=HollowEngine Acoustic Integration
version=${version}
entry=ru.hollowhorizon.hollowengine.addons.acoustic.AcousticAddon
environment=common
requiredClasses=org.bmp.acoustic.AcousticApi,org.bmp.acoustic.client.source.AcousticClientAttachments
