name: Telegram Multi-Notification

on:
  push:
    branches: [ main, master, dev ]
  pull_request:
    types: [opened, closed]
  issues:
    types: [opened, closed]

jobs:
  telegram-notify:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Notification Text
        id: format
        run: |
          REPO="${{ github.repository }}"
          EVENT="${{ github.event_name }}"
          ACTOR="<a href='https://github.com/${{ github.actor }}'>@${{ github.actor }}</a>"
          
          if [ "$EVENT" = "push" ]; then
            TEXT="🚀 <b>PUSH</b> в репозиторий <a href='${{ github.event.compare }}'>$REPO</a>"$'\n'
            TEXT="$TEXT👤 Автор: $ACTOR"$'\n'
            TEXT="$TEXT🌿 Ветка: <code>${{ github.ref_name }}</code>"$'\n'
            TEXT="$TEXT💬 Коммит: <i>${{ github.event.head_commit.message }}</i>"
          
          elif [ "$EVENT" = "pull_request" ]; then
            ACTION="${{ github.event.action }}"
            TEXT="🔀 <b>PULL REQUEST</b> ($ACTION)"$'\n'
            TEXT="$TEXT📁 Репозиторий: $REPO"$'\n'
            TEXT="$TEXT🔗 <a href='${{ github.event.pull_request.html_url }}'>#${{ github.event.pull_request.number }} ${{ github.event.pull_request.title }}</a>"$'\n'
            TEXT="$TEXT👤 Инициатор: $ACTOR"
          
          elif [ "$EVENT" = "issues" ]; then
            ACTION="${{ github.event.action }}"
            TEXT="🐛 <b>ISSUE</b> ($ACTION)"$'\n'
            TEXT="$TEXT📁 Репозиторий: $REPO"$'\n'
            TEXT="$TEXT📌 <a href='${{ github.event.issue.html_url }}'>#${{ github.event.issue.number }} ${{ github.event.issue.title }}</a>"$'\n'
            TEXT="$TEXT👤 Создатель: $ACTOR"
          
          elif [ "$EVENT" = "workflow_run" ]; then
            STATUS="${{ github.event.workflow_run.conclusion }}"
            ICON=$([ "$STATUS" = "success" ] && echo "✅" || echo "❌")
            TEXT="$ICON <b>CHECK RUN:</b> ${{ github.event.workflow_run.name }}"$'\n'
            TEXT="$TEXT📊 Результат: <b>$STATUS</b>"$'\n'
            TEXT="$TEXT🔗 <a href='${{ github.event.workflow_run.html_url }}'>Посмотреть логи билда</a>"
          fi
          
          echo "msg<<EOF" >> $GITHUB_OUTPUT
          echo "$TEXT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send Telegram Message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_CHAT_ID }}
          token: ${{ secrets.TG_BOT_TOKEN }}
          message_thread_id: 4
          format: html
          disable_web_page_preview: true
          message: ${{ steps.format.outputs.msg }}